let data = {
    "total_incidents": 14,
    "total_pages": 1,
    "incidents": [{
        "city_key": "BOY",
        "incident_code": "145315507",
        "incident_date": "2020-08-08T08:16:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at BUFFALO AVE AND PARK PLACE",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.6720619,
        "incident_longitude": -73.9252441,
        "incident_address": "BUFFALO AVE AND PARK PLACE"
    }, {
        "city_key": "BOY",
        "incident_code": "145315504",
        "incident_date": "2020-08-08T07:55:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at 300 BLOCK OF LINDEN BLVD",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.653234,
        "incident_longitude": -73.948134,
        "incident_address": "300 BLOCK OF LINDEN BLVD"
    }, {
        "city_key": "BOY",
        "incident_code": "145308285",
        "incident_date": "2020-08-08T00:00:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at 500 BLOCK OF EAST 84TH ST",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Other",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.6354609,
        "incident_longitude": -73.9644018,
        "incident_address": "500 BLOCK OF EAST 84TH ST"
    }, {
        "city_key": "BOY",
        "incident_code": "145292314",
        "incident_date": "2020-08-07T17:08:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at 100 BLOCK OF BOWERY",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Assault",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.7207796,
        "incident_longitude": -73.9934938,
        "incident_address": "100 BLOCK OF BOWERY"
    }, {
        "city_key": "BOY",
        "incident_code": "145287458",
        "incident_date": "2020-08-07T01:14:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at 800 BLOCK OF SARATOGA AVE",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.658963,
        "incident_longitude": -73.9149304,
        "incident_address": "800 BLOCK OF SARATOGA AVE"
    }, {
        "city_key": "BOY",
        "incident_code": "145267077",
        "incident_date": "2020-08-06T23:19:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at 400 BLOCK OF CLARKSON AVE",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.656253,
        "incident_longitude": -73.942914,
        "incident_address": "400 BLOCK OF CLARKSON AVE"
    }, {
        "city_key": "BOY",
        "incident_code": "145267075",
        "incident_date": "2020-08-06T23:03:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at 2100 BLOCK OF REGENT PLACE",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.646062,
        "incident_longitude": -73.95863,
        "incident_address": "2100 BLOCK OF REGENT PLACE"
    }, {
        "city_key": "BOY",
        "incident_code": "145267068",
        "incident_date": "2020-08-06T22:03:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at SCHENECTADY AVE AND UNION ST",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Other",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.667976,
        "incident_longitude": -73.933982,
        "incident_address": "SCHENECTADY AVE AND UNION ST"
    }, {
        "city_key": "BOY",
        "incident_code": "145267049",
        "incident_date": "2020-08-06T20:32:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at MACDOUGAL ST AND MOTHER GASTON BLVD",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Other",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.680554,
        "incident_longitude": -73.908571,
        "incident_address": "MACDOUGAL ST AND MOTHER GASTON BLVD"
    }, {
        "city_key": "BOY",
        "incident_code": "145267044",
        "incident_date": "2020-08-06T19:22:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at FOSTER AVE AND W YORK AVE",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.6387898,
        "incident_longitude": -73.9453734,
        "incident_address": "FOSTER AVE AND W YORK AVE"
    }, {
        "city_key": "BOY",
        "incident_code": "145267042",
        "incident_date": "2020-08-06T19:15:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at E 82ND ST AND FLATLANDS AVE",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Shooting",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.6365069,
        "incident_longitude": -73.9118337,
        "incident_address": "E 82ND ST AND FLATLANDS AVE"
    }, {
        "city_key": "BOY",
        "incident_code": "145107110",
        "incident_date": "2020-08-03T15:26:00.000Z",
        "incident_offense": "Assault Offenses",
        "incident_offense_code": "13A",
        "incident_offense_description": "Aggravated Assault",
        "incident_offense_detail_description": "Aggravated Assault at COURT ST AND JORALEMON ST",
        "incident_offense_crime_against": "Person",
        "incident_offense_action": "",
        "incident_source_original_type": "Assault",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.6925478,
        "incident_longitude": -73.991,
        "incident_address": "COURT ST AND JORALEMON ST"
    }, {
        "city_key": "BOY",
        "incident_code": "145107108",
        "incident_date": "2020-08-03T15:21:00.000Z",
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery",
        "incident_offense_detail_description": "Robbery at 300 BLOCK OF HUDSON ST",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "",
        "incident_source_original_type": "Robbery",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.72774,
        "incident_longitude": -74.007435,
        "incident_address": "300 BLOCK OF HUDSON ST"
    }, {
        "city_key": "BOY",
        "incident_code": "145107107",
        "incident_date": "2020-08-03T15:19:00.000Z",
        "incident_offense": "Robbery",
        "incident_offense_code": "120",
        "incident_offense_description": "Robbery",
        "incident_offense_detail_description": "Robbery at 300 BLOCK OF HUDSON ST",
        "incident_offense_crime_against": "Property",
        "incident_offense_action": "",
        "incident_source_original_type": "Robbery",
        "incident_source_name": "Brooklyn_Police_Departments",
        "incident_latitude": 40.72774,
        "incident_longitude": -74.007435,
        "incident_address": "300 BLOCK OF HUDSON ST"
    }]
}
let state = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}